export const all_items = [
    { id: 1, name: "Administration", path: "/home/Administration", haveChildren: true, parent_id: null, icon: 'admin.png' }
    , { id: 2, name: "dpp_tp_name", path: "/thirdparty", haveChildren: false, parent_id: 1, icon: 'admin.png' }
    , { id: 3, name: "tpc_newname", path: "/thirdpartycategory", haveChildren: false, parent_id: 1, icon: 'admin.png' }
    , { id: 4, name: "ManageCurrencyrate", path: "/currency", haveChildren: false, parent_id: 1, icon: 'admin.png' }
    , { id: 5, name: "cmp_maincompany", path: "/maincompany", haveChildren: false, parent_id: 1, icon: 'admin.png' }
    , { id: 6, name: "ManageUsers", path: "/manageuser", haveChildren: false, parent_id: 1, icon: 'admin.png' }
    , { id: 7, name: "ManageUsersgroups", path: "/manageusergroup", haveChildren: false, parent_id: 1, icon: 'admin.png' }
    , { id: 8, name: "Employeessalaries", path: "/employeessalaries", haveChildren: false, parent_id: 1, icon: 'admin.png' }
    , { id: 9, name: "Employeesattendance", path: "/employeesattendance", haveChildren: false, parent_id: 1, icon: 'admin.png' }
    , { id: 10, name: "Mandatoryitems", path: "/mandatoryitems", haveChildren: false, parent_id: 1, icon: 'admin.png' }
    , { id: 11, name: "ThirdPartyTransactionType", path: "/thirdpartytransactiontype", haveChildren: false, parent_id: 1, icon: 'admin.png' }
    , { id: 12, name: "RefreshData", path: "/refreshdata", haveChildren: false, parent_id: 1, icon: 'admin.png' }
    , { id: 13, name: "PrinterSetup", path: "/printersetup", haveChildren: false, parent_id: 1, icon: 'admin.png' }
    , { id: 14, name: "Exit", path: "Exit", haveChildren: false, parent_id: 1, icon: 'admin.png' }
    , { id: 15, name: "Item", path: "/home/Items", haveChildren: true, parent_id: null, icon: 'options.png' }
    , { id: 16, name: "ManageItems", path: "/Manageitems", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 17, name: "ItemsFamilies", path: "/itemsfamilies", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 18, name: "ManageExpenses", path: "/manageexprenses", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 19, name: "FixedAssets", path: "/fixedassets", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 20, name: "pu_wa_name", path: "/warehouse", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 21, name: "StockOpening", path: "/stockopening", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 22, name: "StockMovment", path: "/home/Itemssub2", haveChildren: true, parent_id: 15, icon: 'admin.png' }
    , { id: 23, name: "StockIO", path: "/stockio", haveChildren: false, parent_id: 22, icon: 'admin.png' }
    , { id: 24, name: "sa_qty", path: "/adjustitemqty", haveChildren: false, parent_id: 22, icon: 'admin.png' }
    , { id: 25, name: "QTYCostOnHands", path: "/qtycostonhands", haveChildren: false, parent_id: 22, icon: 'admin.png' }
    , { id: 26, name: "ProductionOrder", path: "/productionorder", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 27, name: "ReplaceItemByAnother", path: "/replaceitembyanother", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 28, name: "ReplaceThirdPartyByAnother", path: "/replacethirdpartybyanother", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 29, name: "it_br_name", path: "/brands", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 30, name: "hp_bra_name", path: "/branch", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 31, name: "or_div_name", path: "/division", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 32, name: "pac_co_name", path: "/costcenter", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 33, name: "up_prj_name", path: "/projectjob", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 34, name: "pln_newname", path: "/pricelistname", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 35, name: "hp_pln_name", path: "/pricelist", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 36, name: "TasksAndServices", path: "/taskandserices", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 37, name: "ItemsHistory", path: "/itemshistory", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 38, name: "PricingAndOrdering", path: "/pricingandordering", haveChildren: false, parent_id: 15, icon: 'admin.png' }
    , { id: 39, name: "Purchases", path: "/home/Purchases", haveChildren: true, parent_id: null, icon: 'edit.png' }
    , { id: 40, name: "PurchasesInvoices", path: "/purchaseinvoices", haveChildren: false, parent_id: 39, icon: 'admin.png' }
    , { id: 41, name: "PaymentDebitNote", path: "/paymentdebitnote", haveChildren: false, parent_id: 39, icon: 'admin.png' }
    , { id: 42, name: "Expenses", path: "/expenses", haveChildren: false, parent_id: 39, icon: 'admin.png' }
    , { id: 43, name: "ManageCharge", path: "/managecharge", haveChildren: false, parent_id: 39, icon: 'admin.png' }
    , { id: 44, name: "SplitChargeToPurchases", path: "/splitchargetopuchrases", haveChildren: false, parent_id: 39, icon: 'admin.png' }
    , { id: 45, name: "RequestSupplierOrder", path: "/requestsupplierorder", haveChildren: false, parent_id: 39, icon: 'admin.png' }
    , { id: 46, name: "ChecksGenerator", path: "/checkgenerator", haveChildren: false, parent_id: 39, icon: 'admin.png' }
    , { id: 47, name: "Sales", path: "/home/Sales", haveChildren: true, parent_id: null, icon: 'admin.png' }
    , { id: 48, name: "SalesInvoices", path: "/saleinvoice", haveChildren: false, parent_id: 47, icon: 'admin.png' }
    , { id: 49, name: "ReceiptsCreditNote", path: "/receiptcreditnote", haveChildren: false, parent_id: 47, icon: 'admin.png' }
    , { id: 50, name: "sa_qty", path: "/adjustcostremqty", haveChildren: false, parent_id: 47, icon: 'admin.png' }
    , { id: 51, name: "MyShift", path: "/myshift", haveChildren: false, parent_id: 47, icon: 'admin.png' }
    , { id: 52, name: "transactionType", path: "/transactiontype", haveChildren: false, parent_id: 47, icon: 'admin.png' }
    , { id: 53, name: "ReceiptSetup", path: "/receiptsetup", haveChildren: false, parent_id: 47, icon: 'admin.png' }
    , { id: 54, name: "Reservation", path: "/reservation", haveChildren: false, parent_id: 47, icon: 'admin.png' }
    , { id: 55, name: "InOutThirdParty", path: "/inoutthirdparty", haveChildren: false, parent_id: 47, icon: 'admin.png' }
    , { id: 56, name: "LoyalityProgram", path: "/loyalityprogram", haveChildren: false, parent_id: 47, icon: 'admin.png' }
    , { id: 57, name: "RecalculateTransaction", path: "/recalculatetransaction", haveChildren: false, parent_id: 47, icon: 'admin.png' }
    , { id: 58, name: "ManageStations", path: "/managestations", haveChildren: false, parent_id: 47, icon: 'admin.png' }
    , { id: 59, name: "POS", path: "/home/POS", haveChildren: true, parent_id: null, icon: 'admin.png' }
    , { id: 60, name: "POSMenu", path: "/posmenu", haveChildren: false, parent_id: 59, icon: 'admin.png' }
    , { id: 61, name: "POSButtons", path: "/posbutton", haveChildren: false, parent_id: 59, icon: 'admin.png' }
    , { id: 62, name: "POSStations", path: "/posstation", haveChildren: false, parent_id: 59, icon: 'admin.png' }
    , { id: 63, name: "TablesSections", path: "/home/tableSections", haveChildren: true, parent_id: 59, icon: 'admin.png' }
    , { id: 64, name: "Tables", path: "/tables", haveChildren: false, parent_id: 63, icon: 'admin.png' }
    , { id: 65, name: "Sections", path: "/sections", haveChildren: false, parent_id: 63, icon: 'admin.png' }
    , { id: 66, name: "ManageDisplay", path: "/managedisplay", haveChildren: false, parent_id: 59, icon: 'admin.png' }
    , { id: 67, name: "TableManagment", path: "/tablemanagment", haveChildren: false, parent_id: 59, icon: 'admin.png' }
    , { id: 68, name: "POSExtraItems", path: "/posextraitems", haveChildren: false, parent_id: 59, icon: 'admin.png' }
    , { id: 69, name: "VoidReasons", path: "/voidreasons", haveChildren: false, parent_id: 59, icon: 'admin.png' }
    , { id: 70, name: "PaidOut_PaidIn", path: "/paidoutpaidin", haveChildren: false, parent_id: 59, icon: 'admin.png' }
    , { id: 71, name: "POSItemOptions", path: "/positemoptions", haveChildren: false, parent_id: 59, icon: 'admin.png' }
    , { id: 72, name: "PriceChecker", path: "/pricechecker", haveChildren: false, parent_id: 59, icon: 'admin.png' }
    , { id: 73, name: "Ledger", path: "/home/Ledger", haveChildren: true, parent_id: null, icon: 'admin.png' }
    , { id: 74, name: "ChartsType", path: "ChartType", haveChildren: false, parent_id: 73, icon: 'admin.png' }
    , { id: 75, name: "Charts", path: "Chart", haveChildren: false, parent_id: 73, icon: 'admin.png' }
    , { id: 76, name: "JournalTransaction", path: "JournalTransaction", haveChildren: false, parent_id: 73, icon: 'admin.png' }
    , { id: 77, name: "Banking", path: "Banking", haveChildren: false, parent_id: 73, icon: 'admin.png' }
    , { id: 78, name: "Payroll", path: "Payroll", haveChildren: false, parent_id: 73, icon: 'admin.png' }
    , { id: 79, name: "ExchangeDiffrence", path: "Exchangediffrence", haveChildren: false, parent_id: 73, icon: 'admin.png' }
    , { id: 80, name: "EndOfPeriod", path: "EndofPeriod", haveChildren: false, parent_id: 73, icon: 'admin.png' }
    , { id: 81, name: "PostingParameters", path: "Postingparameters", haveChildren: false, parent_id: 73, icon: 'admin.png' }
    , { id: 82, name: "DivisionPostingParameters", path: "DivisionPostingparameters", haveChildren: false, parent_id: 73, icon: 'admin.png' }
    , { id: 83, name: "Posting", path: "Posting", haveChildren: false, parent_id: 73, icon: 'admin.png' }
    , { id: 84, name: "PostBulkInvoices", path: "PostBulkinvoices", haveChildren: false, parent_id: 73, icon: 'admin.png' }
    , { id: 85, name: "Depreciation", path: "Depreciation", haveChildren: false, parent_id: 73, icon: 'admin.png' }
    , { id: 86, name: "MoveJVsfromAcctoAcc", path: "MoveJVsfromAcctoAcc", haveChildren: false, parent_id: 73, icon: 'admin.png' }
    , { id: 87, name: "AccountingReportTemplates", path: "Accountingreporttemplates", haveChildren: false, parent_id: 73, icon: 'admin.png' }
    , { id: 88, name: "ThirdPartyDefaultAcc", path: "ThirdPartydefaultAcc", haveChildren: false, parent_id: 73, icon: 'admin.png' }
    , { id: 89, name: "Reports", path: "/home/Reports", haveChildren: true, parent_id: null, icon: 'report.png' }
    , { id: 90, name: "hr_tp_name", path: "/home/rep-clients", haveChildren: true, parent_id: 89, icon: 'admin.png' }
    , { id: 91, name: "SalesReports", path: "SalesReports", haveChildren: false, parent_id: 90, icon: 'admin.png' }
    , { id: 92, name: "DuesClients", path: "/home/dueClient", haveChildren: true, parent_id: 90, icon: 'admin.png' }
    , { id: 93, name: "WithUnAllocated", path: "WithunAllocated", haveChildren: false, parent_id: 92, icon: 'admin.png' }
    , { id: 94, name: "InvoicesOnly", path: "InvoicesOnly", haveChildren: false, parent_id: 92, icon: 'admin.png' }
    , { id: 95, name: "UnallocatedOnly", path: "Unallocatedonly", haveChildren: false, parent_id: 92, icon: 'admin.png' }
    , { id: 96, name: "DuesClientsSum", path: "/home/dueClientsum", haveChildren: true, parent_id: 90, icon: 'admin.png' }
    , { id: 97, name: "WithUnAllocated", path: "WithunAllocated", haveChildren: false, parent_id: 96, icon: 'admin.png' }
    , { id: 98, name: "InvoicesOnly", path: "InvoicesOnly", haveChildren: false, parent_id: 96, icon: 'admin.png' }
    , { id: 99, name: "UnallocatedOnly", path: "Unallocatedonly", haveChildren: false, parent_id: 96, icon: 'admin.png' }
    , { id: 100, name: "ListOfNewClients", path: "ListofnewClients", haveChildren: false, parent_id: 96, icon: 'admin.png' }
    , { id: 101, name: "ListOfThirdParty", path: "ListofThirdParty", haveChildren: false, parent_id: 96, icon: 'admin.png' }
    , { id: 102, name: "ListOfDueClients", path: "Listofduesclients", haveChildren: false, parent_id: 96, icon: 'admin.png' }
    , { id: 103, name: "ListOfReceipts", path: "Listofreceipts", haveChildren: false, parent_id: 96, icon: 'admin.png' }
    , { id: 104, name: "ClientStatment", path: "Clientstatment", haveChildren: false, parent_id: 96, icon: 'admin.png' }
    , { id: 105, name: "ThirdPartiesStatment", path: "ThirdPartystatment", haveChildren: false, parent_id: 96, icon: 'admin.png' }
    , { id: 106, name: "Salesorder", path: "Salesorder", haveChildren: false, parent_id: 96, icon: 'admin.png' }
    , { id: 107, name: "Operationsdetails", path: "Operationsdetails", haveChildren: false, parent_id: 96, icon: 'admin.png' }
    , { id: 108, name: "OperationsSummury", path: "OperationsSummury", haveChildren: false, parent_id: 96, icon: 'admin.png' }
    , { id: 109, name: "ClientOperations", path: "/home/clientOperations", haveChildren: true, parent_id: 90, icon: 'admin.png' }
    , { id: 112, name: "Clientsitems", path: "Clients-items", haveChildren: false, parent_id: 90, icon: 'admin.png' }
    , { id: 113, name: "Salesspecials", path: "Salesspecials", haveChildren: false, parent_id: 90, icon: 'admin.png' }
    , { id: 114, name: "Projectanalysis", path: "Projectanalysis", haveChildren: false, parent_id: 90, icon: 'admin.png' }
    , { id: 116, name: "SalesSummary", path: "/salesSammary", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 117, name: "Itemssalesprofit", path: "/home/itemsSalesProfit", haveChildren: true, parent_id: 115, icon: 'admin.png' }
    , { id: 118, name: "Byitems", path: "Byitems", haveChildren: false, parent_id: 117, icon: 'admin.png' }
    , { id: 119, name: "ByInvoiceDetailed", path: "ByInvoice-Detailed", haveChildren: false, parent_id: 117, icon: 'admin.png' }
    , { id: 120, name: "ByClientDetailed", path: "ByClient-Detailed", haveChildren: false, parent_id: 117, icon: 'admin.png' }
    , { id: 121, name: "Byclientbyinvoicedetailed", path: "Byclient-byinvoice-detailed", haveChildren: false, parent_id: 117, icon: 'admin.png' }
    , { id: 122, name: "BySupplierdetailed", path: "BySupplier-detailed", haveChildren: false, parent_id: 117, icon: 'admin.png' }
    , { id: 123, name: "Byinvoicesummarized", path: "Byinvoice-summarized", haveChildren: false, parent_id: 117, icon: 'admin.png' }
    , { id: 124, name: "Byclientbyinvoicesummarized", path: "Byclient-byinvoice-summarized", haveChildren: false, parent_id: 117, icon: 'admin.png' }
    , { id: 125, name: "Byclientsummarized", path: "Byclient-summarized", haveChildren: false, parent_id: 117, icon: 'admin.png' }
    , { id: 126, name: "Bysuppliersummarized", path: "Bysupplier-summarized", haveChildren: false, parent_id: 117, icon: 'admin.png' }
    , { id: 127, name: "Byitemwithimages", path: "Byitemwithimages", haveChildren: false, parent_id: 117, icon: 'admin.png' }
    , { id: 128, name: "Byfamilybyitemsummarized", path: "Byfamily-byitem-summarized", haveChildren: false, parent_id: 117, icon: 'admin.png' }
    , { id: 129, name: "Byfamilybyitemdetailed", path: "Byfamily-byitem-detailed", haveChildren: false, parent_id: 117, icon: 'admin.png' }
    , { id: 130, name: "YearlyMonthlydetailed", path: "Yearly-Monthly-detailed", haveChildren: false, parent_id: 117, icon: 'admin.png' }
    , { id: 131, name: "YearlyMonthlysummarized", path: "Yearly-Monthly-summarized", haveChildren: false, parent_id: 117, icon: 'admin.png' }
    , { id: 132, name: "YearlyMonthlyBycodedetailed", path: "Yearly-Monthly-Bycode-detailed", haveChildren: false, parent_id: 117, icon: 'admin.png' }
    , { id: 133, name: "YearlyMonthlyBycodesummarized", path: "Yearly-Monthly-Bycode-summarized", haveChildren: false, parent_id: 117, icon: 'admin.png' }
    , { id: 134, name: "ItemssalesbyunitPrice", path: "ItemssalesbyunitPrice", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 135, name: "BestsellingAmt", path: "BestsellingAmt", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 136, name: "BestsellingQty", path: "BestsellingQty", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 137, name: "ItembyFamily", path: "/home/itemByFamily", haveChildren: true, parent_id: 115, icon: 'admin.png' }
    , { id: 140, name: "Itemprofitsum", path: "Itemprofit-sum", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 142, name: "ByInvoice", path: "ByInvoice", haveChildren: false, parent_id: 141, icon: 'admin.png' }
    , { id: 143, name: "ByemployeeByCategory", path: "ByemployeeByCategory", haveChildren: false, parent_id: 141, icon: 'admin.png' }
    , { id: 144, name: "Byemployee", path: "Byemployee", haveChildren: false, parent_id: 141, icon: 'admin.png' }
    , { id: 145, name: "ByCategory", path: "ByCategory", haveChildren: false, parent_id: 141, icon: 'admin.png' }
    , { id: 146, name: "CollectionMode", path: "CollectionMode", haveChildren: false, parent_id: 141, icon: 'admin.png' }
    , { id: 147, name: "Salesbyemployeecommission", path: "Salesbyemployee/commission", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 148, name: "Freeitems", path: "Freeitems", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 149, name: "Sellingpricechanged", path: "Sellingpricechanged", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 150, name: "Salesandpurchasesanalysis", path: "Salesandpurchasesanalysis", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 151, name: "Hourlysales", path: "Hourlysales", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 152, name: "Dailysales", path: "Dailysales", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 153, name: "Salesbyshift", path: "Salesbyshift", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 154, name: "TipsDaily", path: "Tips-Daily", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 155, name: "Monthlysales", path: "Monthlysales", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 156, name: "Yearlysales", path: "Yearlysales", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 157, name: "Salesinvoicecount", path: "Salesinvoicecount", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 158, name: "Salesanalysis", path: "Salesanalysis", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 159, name: "salesprogress", path: "salesprogress", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 160, name: "Voidreport", path: "Voidreport", haveChildren: false, parent_id: 115, icon: 'admin.png' }
    , { id: 161, name: "SupplierPayables", path: "/home/rep-SupplierPaybles", haveChildren: true, parent_id: 89, icon: 'admin.png' }
    , { id: 162, name: "Purchasesreport", path: "Purchasesreport", haveChildren: false, parent_id: 161, icon: 'admin.png' }
    , { id: 163, name: "DuessupplierPayables", path: "Duessupplier/Payables", haveChildren: false, parent_id: 161, icon: 'admin.png' }
    , { id: 164, name: "ListofDuessupplier", path: "ListofDuessupplier", haveChildren: false, parent_id: 161, icon: 'admin.png' }
    , { id: 165, name: "Listofpayments", path: "Listofpayments", haveChildren: false, parent_id: 161, icon: 'admin.png' }
    , { id: 166, name: "Listofreceiptspaymentssum", path: "Listofreceipts-paymentssum", haveChildren: false, parent_id: 161, icon: 'admin.png' }
    , { id: 167, name: "Supplierstatment", path: "Supplierstatment", haveChildren: false, parent_id: 161, icon: 'admin.png' }
    , { id: 168, name: "Purchaseorders", path: "Purchaseorders", haveChildren: false, parent_id: 161, icon: 'admin.png' }
    , { id: 169, name: "SupplierOperationsDetail", path: "SupplierOperationsDetail", haveChildren: false, parent_id: 161, icon: 'admin.png' }
    , { id: 170, name: "SupplierOperationsDetail1", path: "SupplierOperationsDetail1", haveChildren: false, parent_id: 161, icon: 'admin.png' }
    , { id: 171, name: "Suppliersitems", path: "Suppliers-items", haveChildren: false, parent_id: 161, icon: 'admin.png' }
    , { id: 172, name: "purchasescharges", path: "purchasescharges", haveChildren: false, parent_id: 161, icon: 'admin.png' }
    , { id: 174, name: "Stockstatus", path: "Stockstatus", haveChildren: false, parent_id: 173, icon: 'admin.png' }
    , { id: 175, name: "stockmovment", path: "stockmovment", haveChildren: false, parent_id: 173, icon: 'admin.png' }
    , { id: 176, name: "stockadjusment", path: "stockadjusment", haveChildren: false, parent_id: 173, icon: 'admin.png' }
    , { id: 177, name: "stockevaluation", path: "stockevaluation", haveChildren: false, parent_id: 173, icon: 'admin.png' }
    , { id: 178, name: "QuantitiesonHands", path: "QuantitiesonHands", haveChildren: false, parent_id: 173, icon: 'admin.png' }
    , { id: 179, name: "Sizeandcolor", path: "Sizeandcolor", haveChildren: false, parent_id: 173, icon: 'admin.png' }
    , { id: 180, name: "Pricelistreport", path: "Pricelistreport", haveChildren: false, parent_id: 173, icon: 'admin.png' }
    , { id: 181, name: "Expirydate", path: "Expirydate", haveChildren: false, parent_id: 173, icon: 'admin.png' }
    , { id: 182, name: "Serialnumber", path: "Serialnumber", haveChildren: false, parent_id: 173, icon: 'admin.png' }
    , { id: 183, name: "Stockage", path: "Stockage", haveChildren: false, parent_id: 173, icon: 'admin.png' }
    , { id: 185, name: "Listofitems", path: "Listofitems", haveChildren: false, parent_id: 184, icon: 'admin.png' }
    , { id: 186, name: "Listofitemswithimages", path: "Listofitemswithimages", haveChildren: false, parent_id: 184, icon: 'admin.png' }
    , { id: 187, name: "Itemstechnicalsheet", path: "/home/itemTechSheet", haveChildren: true, parent_id: 184, icon: 'admin.png' }
    , { id: 188, name: "Allitems", path: "Allitems", haveChildren: false, parent_id: 187, icon: 'admin.png' }
    , { id: 189, name: "WithSubItemsOny", path: "WithSubItemsOny", haveChildren: false, parent_id: 187, icon: 'admin.png' }
    , { id: 190, name: "SubItemslist", path: "SubItemslist", haveChildren: false, parent_id: 184, icon: 'admin.png' }
    , { id: 192, name: "Journaloperations", path: "Journaloperations", haveChildren: false, parent_id: 191, icon: 'admin.png' }
    , { id: 193, name: "GeneralLedger", path: "GeneralLedger", haveChildren: false, parent_id: 191, icon: 'admin.png' }
    , { id: 194, name: "Statmentofaccount", path: "Statmentofaccount", haveChildren: false, parent_id: 191, icon: 'admin.png' }
    , { id: 195, name: "Trialbalance", path: "Trialbalance", haveChildren: false, parent_id: 191, icon: 'admin.png' }
    , { id: 196, name: "Profitandloss", path: "Profitandloss", haveChildren: false, parent_id: 191, icon: 'admin.png' }
    , { id: 197, name: "Balancesheet", path: "Balancesheet", haveChildren: false, parent_id: 191, icon: 'admin.png' }
    , { id: 198, name: "VATreport", path: "VATreport", haveChildren: false, parent_id: 191, icon: 'admin.png' }
    , { id: 199, name: "Cashflowaging", path: "Cashflow/aging", haveChildren: false, parent_id: 191, icon: 'admin.png' }
    , { id: 200, name: "productionAnalysis", path: "/home/rep-productionAnalysis", haveChildren: true, parent_id: 89, icon: 'admin.png' }
    , { id: 201, name: "Itemssold", path: "/home/itemSold", haveChildren: true, parent_id: 200, icon: 'admin.png' }
    , { id: 202, name: "Itemssum", path: "Items-sum", haveChildren: false, parent_id: 201, icon: 'admin.png' }
    , { id: 203, name: "ItemsDetailed", path: "Items-Detailed", haveChildren: false, parent_id: 201, icon: 'admin.png' }
    , { id: 204, name: "Monthsum", path: "Month-sum", haveChildren: false, parent_id: 201, icon: 'admin.png' }
    , { id: 205, name: "MonthDetailed", path: "Month-Detailed", haveChildren: false, parent_id: 201, icon: 'admin.png' }
    , { id: 206, name: "WeekDaysum", path: "WeekDay-sum", haveChildren: false, parent_id: 201, icon: 'admin.png' }
    , { id: 207, name: "WeekDayDetailed", path: "WeekDay-Detailed", haveChildren: false, parent_id: 201, icon: 'admin.png' }
    , { id: 208, name: "MonthWeekDaysum", path: "Month-WeekDay-sum", haveChildren: false, parent_id: 201, icon: 'admin.png' }
    , { id: 209, name: "MonthWeekDayDetailed", path: "Month-WeekDay-Detailed", haveChildren: false, parent_id: 201, icon: 'admin.png' }
    , { id: 210, name: "Itemsused", path: "/home/itemUsed", haveChildren: true, parent_id: 200, icon: 'admin.png' }
    , { id: 211, name: "Itemssum", path: "Items-sum", haveChildren: false, parent_id: 210, icon: 'admin.png' }
    , { id: 212, name: "ItemsDetailed", path: "Items-Detailed", haveChildren: false, parent_id: 210, icon: 'admin.png' }
    , { id: 213, name: "Monthsum", path: "Month-sum", haveChildren: false, parent_id: 210, icon: 'admin.png' }
    , { id: 214, name: "MonthDetailed", path: "Month-Detailed", haveChildren: false, parent_id: 210, icon: 'admin.png' }
    , { id: 215, name: "WeekDaysum", path: "WeekDay-sum", haveChildren: false, parent_id: 210, icon: 'admin.png' }
    , { id: 216, name: "WeekDayDetailed", path: "WeekDay-Detailed", haveChildren: false, parent_id: 210, icon: 'admin.png' }
    , { id: 217, name: "MonthWeekDaysum", path: "Month-WeekDay-sum", haveChildren: false, parent_id: 210, icon: 'admin.png' }
    , { id: 218, name: "MonthWeekDayDetailed", path: "Month-WeekDay-Detailed", haveChildren: false, parent_id: 210, icon: 'admin.png' }
    , { id: 219, name: "ItemsGenerated", path: "/home/itemGenerated", haveChildren: true, parent_id: 200, icon: 'admin.png' }
    , { id: 220, name: "Itemssum", path: "Items-sum", haveChildren: false, parent_id: 219, icon: 'admin.png' }
    , { id: 221, name: "ItemsDetailed", path: "Items-Detailed", haveChildren: false, parent_id: 219, icon: 'admin.png' }
    , { id: 222, name: "Monthsum", path: "Month-sum", haveChildren: false, parent_id: 219, icon: 'admin.png' }
    , { id: 223, name: "MonthDetailed", path: "Month-Detailed", haveChildren: false, parent_id: 219, icon: 'admin.png' }
    , { id: 224, name: "WeekDaysum", path: "WeekDay-sum", haveChildren: false, parent_id: 219, icon: 'admin.png' }
    , { id: 225, name: "WeekDayDetailed", path: "WeekDay-Detailed", haveChildren: false, parent_id: 219, icon: 'admin.png' }
    , { id: 226, name: "MonthWeekDaysum", path: "Month-WeekDay-sum", haveChildren: false, parent_id: 219, icon: 'admin.png' }
    , { id: 227, name: "MonthWeekDayDetailed", path: "Month-WeekDay-Detailed", haveChildren: false, parent_id: 219, icon: 'admin.png' }
    , { id: 228, name: "Monthlysalesbyitem", path: "Monthlysalesbyitem", haveChildren: false, parent_id: 200, icon: 'admin.png' }
    , { id: 229, name: "MonthlysalesbyitemCode", path: "MonthlysalesbyitemCode", haveChildren: false, parent_id: 200, icon: 'admin.png' }
    , { id: 230, name: "Estimatedconsumed", path: "Estimated-consumed", haveChildren: false, parent_id: 200, icon: 'admin.png' }
    , { id: 231, name: "CostCenter", path: "/home/rep-CostCenter", haveChildren: true, parent_id: 89, icon: 'admin.png' }
    , { id: 232, name: "ByEntry", path: "ByEntry", haveChildren: false, parent_id: 231, icon: 'admin.png' }
    , { id: 233, name: "ByCostcenter", path: "ByCostcenter", haveChildren: false, parent_id: 231, icon: 'admin.png' }
    , { id: 235, name: "ByEntry", path: "ByEntry", haveChildren: false, parent_id: 234, icon: 'admin.png' }
    , { id: 237, name: "ThirdPartyTaskDet", path: "ThirdPartyTask-Det", haveChildren: false, parent_id: 236, icon: 'admin.png' }
    , { id: 238, name: "ThirdPartyTaskSum", path: "ThirdPartyTask-Sum", haveChildren: false, parent_id: 236, icon: 'admin.png' }
    , { id: 239, name: "ThirdPartyTaskDetWithoutitem", path: "ThirdPartyTask-Det-Withoutitem", haveChildren: false, parent_id: 236, icon: 'admin.png' }
    , { id: 240, name: "ThirdPartyTaskSumWithoutitem", path: "ThirdPartyTask-Sum-Withoutitem", haveChildren: false, parent_id: 236, icon: 'admin.png' }
    , { id: 247, name: "Remotesupport", path: "Remotesupport", haveChildren: false, parent_id: 241, icon: 'admin.png' }
    , { id: 248, name: "Databasemanagment", path: "Databasemanagment", haveChildren: false, parent_id: 241, icon: 'admin.png' }
];
